development: &defaults
  adapter: postgresql
  database: family_budget_development
  username: family_budget

test:
  <<: *defaults
  database: family_budget_test

staging:
  <<: *defaults
  database: family_budget_staging
